name: Integration
on:
  pull_request:
    branches: [master, develop, alpha]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-18.04
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    steps:
      - name: Checkout
        id: setup-1
        uses: actions/checkout@v1

      - name: Install Nix
        id: setup-2
        uses: cachix/install-nix-action@v10
        with:
          skip_adding_nixpkgs_channel: true

      - name: Cachix
        id: setup-3
        uses: cachix/cachix-action@v6
        with:
          name: mirror
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Download Nix Dependenices
        id: setup-4
        run: |
          nix-shell

  test:
    name: Test
    needs: setup
    runs-on: ubuntu-18.04
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    steps:
      - name: Checkout
        id: test-1
        uses: actions/checkout@v1

      - name: Install Nix
        id: test-3
        uses: cachix/install-nix-action@v10

      - name: Cachix
        id: test-4
        uses: cachix/cachix-action@v6
        with:
          name: mirror
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run tests
        id: test-5
        run: |
          nix-shell --run "make test"

      - name: Upload coverage to Codecov
        id: test-6
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          # TODO (sam): change after refactor
          fail_ci_if_error: false

      - name: Upload Test Artifacts
        id: test-7
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: ./target/test/**/*
          